### PR TITLE
Move information about model differences to a configuration file

### PR DESCRIPTION
**Pull request by chrissearle**
I was getting worried about the sheer amount of custom code turning up in ControllerUtils about model differences.

This change creates a config file that holds that information in one place.

The concept is that the config file has a defaults section - with a default value for each type of field (currently default shots per row, gimbal yaw relative and switch position) as well as a section for each field type where we can - per model - override.

See ModelConfig.plist for values.

Doesn't yet handle Phantom 4 Pro - since I can't see a constant in https://developer.dji.com/iframe/mobile-sdk-doc/ios/Constants.html for it.

### CODE REVIEW

**Comment by chrissearle** [comment]
Can't see a constant for the Inspire 2 either

**Comment by chrissearle** [comment]
P4 Pro is now present. i2 isn't - since I don't know what settings it needs. If it uses the defaults (switch F, relative gimbal yaw and 6 per row) then it's all good anyway.

**Comment by chrissearle** [comment]
Need to switch from flight mode to switch position

**Review by dbaldwin — APPROVED** [review]
I will test with P4, I1, and Mavic Pro

**Pull request merged**
