### PR TITLE
File logger and ability to copy it to clipboard from settings window.

### PR DESCRIPTION
**Pull request by chrissearle**
This pull request does several things.
- AppDelegate moved to swift
- Carthage utility used to add CocoaLumberjack frameworks
- Loggers for ASL (apple system logs), TTY (xcode console) and file added (the first two are pretty standard to all projects, the file logger is what we need here).
- Method added to app delegate to copy current logfile to clipboard
- Button added to settings view to trigger this
- All NSLog changed to relevant DDLog\* calls
- Much more logging added to make the log more useful
- Log level set to debug (so DDLogVerbose is left out - used mostly for really chatty delegates - can be enabled for development but not normally included)

Carthage is easiest to install with homebrew

```
brew install carthage
```

After the first pull - you will need to run

```
carthage bootstrap
```

We don't check in Carthage/\* so we don't have copies of other libraries included in our repository

Note that this also adds a Run Script build phase which runs the following:

```
/usr/local/bin/carthage copy-frameworks
```

for both CocoaLumberjack and the swift wrapper CocoaLumberjackSwift, so you will need carthage installed for that too.

### CODE REVIEW

**Comment by chrissearle** [comment]
Sample successful Osmo run with raw+jpg showing retry due to file saving taking longer (the raw bit).

[successful_log.txt](https://github.com/dbaldwin/DronePan/files/233583/successful_log.txt)

**Comment by chrissearle** [comment]
Error test - unplug and replug SD card.

[unplug_and_replug_sd_card.txt](https://github.com/dbaldwin/DronePan/files/233618/unplug_and_replug_sd_card.txt)

**Comment by dbaldwin** [comment]
Looks good. I'm going to pull and build.

**Comment by dbaldwin** [comment]
This is working well. Nice job!

**Pull request merged**
